### ISSUE TITLE
stop caching lightcurves during sampling -- add in post-processing

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#134]
During sampling we went above the requested RAM (I requested 4GB)

**Comment by avivajpeyi** [comment]
Hey @dfm I think ive understood how to get a compiled version of the model using `theano.function`.  

Based on that, would something like the following be a reasonable thing for me to try:

1. add a `create_lightcurve` function
2. use the `create_lightcurve` function within our `pm.model` (this way our lightcurve-model is defined once but used in both our `pm.model`and in post-processing)
3. for post-processing, use a compiled version of the `create_lightcurve` function for the processing

https://github.com/dfm/tess-atlas/blob/401cf6a24fe25a7489423367cf55ece636f5a554/src/tess_atlas/notebook_templates/toi_template.py#L181


Sidenote: although still a bit confusing, I think I'm beginning to see how cool pymc3 is! Up till now, I've mainly used dynesty for all my bayesian needs :)

**Comment by dfm** [comment]
A good way to start might be to use a function like this and then pass in the appropriate parameters. In older versions of PyMC, I had functions to automate this (handling parameter transformations, etc.) see:

- https://github.com/exoplanet-dev/pymc3-ext/blob/c2696b3c9244661a3e8e240c22d2f1193c561922/src/pymc3_ext/utils.py#L91
- https://github.com/exoplanet-dev/pymc3-ext/blob/c2696b3c9244661a3e8e240c22d2f1193c561922/src/pymc3_ext/utils.py#L43
- https://github.com/exoplanet-dev/pymc3-ext/blob/c2696b3c9244661a3e8e240c22d2f1193c561922/src/pymc3_ext/utils.py#L24

But unfortunately I don't think that this logic will work out of the box with the ArviZ traces, since ArviZ doesn't save the transformed variables: https://github.com/arviz-devs/arviz/issues/230

**Comment by avivajpeyi** [comment]
Hey @dfm ! 

I used the above functions to compute the variables (vars) we need in post-processing. However, this only works when the var is stored as a `Deterministic` (see the `main` function below, snipped marked `(b)`). 

As you point above, I'm unsure how to get the var in post-processing when I haven't stored the var in the model as a `Deterministic` var. 

I tried looking at `az.inference_data`'s docs to figure this out without much success. I also investigated if we could hack up the [`refitting PyMC3 models with ArviZ` example](https://arviz-devs.github.io/arviz/user_guide/pymc3_refitting.html) to cache the vars, but made little progress... hmm

For the sake of time, moving forward, can we either:
1. Stop converting to `az` and keep the `pymc3.MultiTrace` object?  
    - I think I can see how to calculate  vars from `pymc3.MultiTrace` during post-processing
2. Cache the data during sampling using `Deterministic` (and incur the memory issues)

Another option may be to inherit and modify `az.InferenceData`, but I think this will take time. 




*** 
##### code to test post-processing 
 
```python
import numpy as np
import pymc3 as pm
import arviz as az
from typing import Tuple
import matplotlib.pyplot as plt
import pandas as pd


np.random.seed(42)

TRUES = dict(m=0.5, b=-1.3, logs=np.log(0.3))

def generate_line_data(m, b, logs)->Tuple[np.ndarray, np.ndarray]:
    x = np.sort(np.random.uniform(0, 5, 50))
    y = b + m * x + np.exp(logs) * np.random.randn(len(x))
    return x, y

def create_line_model(x,y, cache_predictions)->pm.Model:
    with pm.Model() as line_model:
        m = pm.Uniform("m", lower=-5, upper=5)
        b = pm.Uniform("b", lower=-5, upper=5)
        logs = pm.Uniform("logs", lower=-5, upper=5)
        
        line = m*x+b
        if cache_predictions:
            line = pm.Deterministic("line", line)
            
        pm.Normal("obs", mu=line, sd=pm.math.exp(logs), observed=y)
    return line_model

def run_parameter_estimation(model)->az.InferenceData:
    sampling_kwargs = dict(draws=100, tune=100, chains=2)
    with model:
        trace = pm.sample(**sampling_kwargs)
    idata =  az.from_pymc3(trace, model=model)
    return idata

def get_quants_from_predections(predictions, quantiles=[16,50,84]):
    quants = np.percentile(predictions, [16, 50, 84], axis=(0, 1))
    return quants


def plot(x, y, predictions=[], title=""):
    plt.figure(figsize=(3,3))
    plt.plot(x, y, ".k", label="Data")
    plt.xlabel("x", fontsize='x-large')
    plt.ylabel("y", fontsize='x-large')
    if len(predictions) > 0:
        prediction_quants = get_quants_from_predections(predictions)
        plt.fill_between(x, quants[0, :], quants[2, :], color="C0", alpha=0.5)
        plt.plot(x, quants[1, :], color="C0", label="Prediction")        
    plt.legend(loc='upper left', bbox_to_anchor=(1.01, 1), frameon=False)
    plt.xlim(min(x), max(x))
    plt.ylim(min(y), max(y))
    plt.title(title)
    
def calculate_predictions_in_post_processing(model, idata, prediction_label):
    samples = get_posterior_samples(idata).to_numpy()
    
    with model:
        pred_var = model[prediction_label]
        pred_func = get_theano_function_for_var(pred_var)
        predictions = [pred_func(*i) for i in samples]

    return predictions

def get_posterior_samples(idata)-> pd.DataFrame:
    return idata.to_dataframe(groups=["posterior"])[['m', 'b', 'logs']]

def main():
    data_x, data_y = generate_line_data(**TRUES)

    # (a) predictions cached in model as 'Deterministic'
    line_model = create_line_model(data_x, data_y, cache_predictions=True)
    idata = run_parameter_estimation(line_model)
    predictions = idata.posterior.line.values
    plot(data_x, data_y, predictions, "`line` Deterministic ")

    # (b) predictions calcualted in post-proc (line var stored as deterministic)
    predictions = calculate_predictions_in_post_processing(line_model, idata, 'line')
    plot(data_x, data_y, predictions, "`line` Deterministic + PostProcessing ")

    # (c) predictions not cached in model (just evaluated as line=...)
    line_model_no_cache = create_line_model(data_x, data_y, cache_predictions=False)
    idata_no_cache = run_parameter_estimation(line_model_no_cache)
    predictions = []
    plot(data_x, data_y, predictions, "`line` not Deterministic")
    


if __name__ == "__main__":
    main()



```

**Comment by dfm** [comment]
Here's the function that I put together to do this more generally:

```python
import theano
from pymc3.util import get_default_varnames, get_untransformed_name, is_transformed_name

def compute_value_in_post(model, idata, target, size=None):
    # Get the names of the untransformed variables
    vars = get_default_varnames(model.unobserved_RVs, True)
    names = list(sorted(set([
        get_untransformed_name(v.name)
        if is_transformed_name(v.name)
        else v.name
        for v in vars
    ])))

    # Compile a function to compute the target
    func = theano.function([model[n] for n in names], target, on_unused_input="ignore")

    # Call this function for a bunch of values
    flat_samps = idata.posterior.stack(sample=("chain", "draw"))
    if size is None:
        indices = np.arange(len(flat_samps.sample))
    else:
        indices = np.random.randint(len(flat_samps.sample), size=size)

    return [func(*(flat_samps[n].values[..., i] for n in names)) for i in indices]
```

The arguments are as follows:

- `model`: The pymc3 model object
- `idata`: The inference data trace
- `target`: The tensor (or list of tensors) that you want to compute for the samples
- `size`: The number of samples to draw (leave it as `None` for all, but that's probably not what we want).

In your test case, I would save a pointer to the mean model tensor, e.g.:

```python
#...
line = m*x+b
line_model.line_tensor = line
#...
```

Then call my function using `compute_value_in_post(line_model, idata, line_model.line_tensor)`.

What do you think of this?

**Comment by avivajpeyi** [comment]
Ah! the pointer to the variable is key! This is great! Thanks :D 

Ill test it out with our transit model :)

**Comment by avivajpeyi** [comment]
Huzza!! 🎆 🥳 🎊 

It works: 
<img width="548" alt="Screen Shot 2021-11-04 at 2 10 44 pm" src="https://user-images.githubusercontent.com/15642823/140251673-c981c54b-446f-4b5a-a492-5288422e4ab0.png">



Will try to get this merged in :)
