### ISSUE TITLE
post-processed lightcurves + other posterior parameters 

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#140]
With #137 we added the ability to compute lightcurves in post-processing. This is quite quick (~1second) to create 1000 lightcurve samples 

```python
  samples = get_posterior_samples(
      inference_data=inference_data,
      varnames=get_untransformed_varnames(model),
      size=1000,
  )
  lcs = compute_variable(
      model=model, samples=samples, target=model.lightcurve_models
  )
```

This will result in an `np.ndarray` of the shape: `(1000 lcs, y-datapoints)`

Now, in the plotting routines that need both the lightcurves and other samples, I am using code such as: 
```python
  # Get the posterior median orbital parameters
  p = np.median(posterior["p"].values[..., i])
  t0 = np.median(posterior["t0"].values[..., i])
```

This will result in samples with the shape `(#chains, #draws)` which is not equal to the shape of the `lcs` array. Additionally, as `lcs`'s rows are randomly sorted, I do not know which sample in the `posterior` the `lcs` correspond to.

So, instead of accessing the samples from `posterior[param].values` I should try to access the samples from the output of `get_posterior_samples`...

**Comment by dfm** [comment]
I don't think you need to worry about this in general. Taking the median of the posterior periods, for example, and overplotting the phased light curves would be fine, we don't need them to be the exact same set of samples.
