### ISSUE TITLE
theano creating too many temp files

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#155]
Slurm doesnt like my array job being ~4500 jobs in size. 

Getting some help from OzStar folks: https://support.hpc.swin.edu.au/servicedesk/customer/portal/1/HPCDESK-3947

**Comment by avivajpeyi** [comment]
The PR #154 splits the slurm submission files into 3 (each submits max_array_size or less jobs)

**Comment by avivajpeyi** [comment]
When I submit with 2048 jobs I still get an error: 
```
Submitting /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/submit/slurm_gen_1_job.sh /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/submit/slurm_pe_1_job.sh
sbatch: error: QOSMaxSubmitJobPerUserLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
sbatch: error: Batch job submission failed: Job dependency problem
```

The smaller array job works: 
```
Submitting /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/submit/slurm_gen_2_job.sh /fred/oz200/avajpeyi/projects/atlas_runs/notebooks/submit/slurm_pe_2_job.sh
Submitted batch job 2457352
```

**Comment by avivajpeyi** [comment]
I've hit the `inode` usage limit argggg 🤦🏽 

```
     Filesystem  kbytes   quota   limit   grace   files   quota   limit   grace
          /fred 45875804       0 10737418240       - 1000000*      0 1000000       -(Disk usage is at 0.4%, 43.8GB of 10240.0GB, Inode usage is at 100.0%)
```

**Comment by avivajpeyi** [comment]
Ok I see some things that we can clear up quickly: 

1) the `./theano_cache/pid`
2) some cache files from MAST `./toi_XYZ_files/mastDownload/`
3) log files for successful runs `./toi_XYZ_files/logs`

**Comment by avivajpeyi** [comment]
Hmm i think i probably should do an `os.walk` to figure out where the `inodes` are getting used

**Comment by avivajpeyi** [comment]
On deleting `toi_*_files/mastDownloads` the `inode` usage went from `100-->99.4%`

**Comment by avivajpeyi** [comment]
woah, deleting `theano_cache`  took us `99.4-->62.6%`

**Comment by dfm** [comment]
This a per-process cache right? It might be worth adding a clean up step to remove that directory as the job finishes?

**Comment by avivajpeyi** [comment]
Yeah -- I think this is the way to go. Should be straightforward enough!

**Comment by avivajpeyi** [comment]
On processing 1 TOI I found that there were > 3000 files created, and 99.6% of these files were in the `theano_cache`. 


Here is a `tree` of the output:

```
.
└── notebooks
    └── 0.2.1.dev48+g585b6df
        ├── tess_atlas_runner.log
        ├── theano_cache
        │   └── **19271 [440 entries exceeds filelimit, not opening dir]**
        ├── toi_103.ipynb
        └── toi_103_files
            ├── flux_vs_time.png
            ├── folded_flux_vs_time.png
            ├── lightcurve.csv
            ├── mastDownload
            │   ├── HLSP
            │   │   └── hlsp_tasoc_tess_ffi_tic00336732616-s01-c0120_tess_v04_lc
            │   │       └── hlsp_tasoc_tess_ffi_tic00336732616-s01-c0120_tess_v04_lc.fits
            │   └── TESS
            │       └── tess2018206045859-s0001-0000000336732616-0120-s
            │           └── tess2018206045859-s0001-0000000336732616-0120-s_lc.fits
            ├── priors.png
            ├── stellar_data.json
            ├── tess_atlas.log
            └── tic_data.csv


2644 directories, 3067 files
```

Inside `theano_cache/19271`, there are a 400+ dirs named `tmp*`. An example of the contents in one of these is shown below:

```
./notebooks/0.2.1.dev48+g585b6df/theano_cache/19271/tmpzyr_8zta/
├── __init__.py
├── __pycache__
│   └── __init__.cpython-39.pyc
├── key.pkl
├── ma722c2ebca13fda9585da5018cfb4ce74de2ded9f031eb21bcbfab0d129bd2fb.so
├── ma722c2ebca13fda9585da5018cfb4ce74de2ded9f031eb21bcbfab0d129bd2fb.so.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── ma722c2ebca13fda9585da5018cfb4ce74de2ded9f031eb21bcbfab0d129bd2fb.so
└── mod.cpp

5 directories, 7 files
```



**Some things to look into: **
1. Why is the theano_cache creating so many of these temp folders? I assumed that it would only need to create it once when the `pymc3` model is compiled? 
2. At what stage can I remove the `tmp` dirs?

**Comment by avivajpeyi** [comment]
I might be able to get away with making the `theano_cache` store files in a scratch space for the job rather than in my project's dirs.
https://supercomputing.swin.edu.au/docs/2-ozstar/oz-partition.html#requesting-local-scratch-space
