### ISSUE TITLE
2min cadence data TOI list is incorrect 

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#236]
We are caching a list of TOIs with 2min cadence data. However: 

## updated TOI cache not accounting for if LK present correctly

We seem to be not getting any TOIs with lightcurves after TOI 3000 in the updated TOI list ... This seems wrong -- previously we had some TOIs > TOI 3000 with 2-min cadence data.
<img width="791" alt="Screen Shot 2022-07-28 at 12 17 34 pm" src="https://user-images.githubusercontent.com/15642823/181587767-02192415-f3c4-456f-a6f3-4c374821ed36.png">

Why are the ~700 TOIs above TOI 3000 previously considered to have data now not have any data? 

```python
import matplotlib.pyplot as plt 
import pandas as pd

current_db  = pd.read_csv("https://raw.githubusercontent.com/dfm/tess-atlas/main/src/tess_atlas/data/cached_tic_database.csv")
old_db = pd.read_csv("https://raw.githubusercontent.com/dfm/tess-atlas/42de954ab7973b548ebb21ebacabe0afbe08c495/src/tess_atlas/data/cached_tic_database.csv")

cur = current_db[current_db["Lightcurve Availible"]==True]["TOI int"].tolist()
old = old_db[old_db["Lightcurve Availible"]==True]["TOI int"].tolist()

cur_mis = current_db[current_db["Lightcurve Availible"]==False]["TOI int"].tolist()
old_mis = old_db[old_db["Lightcurve Availible"]==False]["TOI int"].tolist()


# plot comparison
fig, ax = plt.subplots(2,1, sharex=True, sharey=True, figsize=(20, 2))
r = dict(ymin=0,ymax=2, lw=0.1)
ax[0].vlines(cur, **r, label=f"Current ({len(cur)}/{len(current_db)} TOIs)", color="tab:green")
ax[1].vlines(old, **r, label=f"Old ({len(old)}/{len(old_db)} TOIs)", color="tab:green")
ax[0].vlines(cur_mis, **r, color="tab:red")
ax[1].vlines(old_mis, **r, color="tab:red")
ax[0].set_ylim(0.99,1.01)
ax[0].set_yticks([])
ax[0].legend(loc="upper left",)
ax[1].legend(loc="upper left",)
ax[1].set_xlabel("TOIs with 2-min Lightcurve data", fontsize='xx-large')
ax[1].set_xlim(100, 5794)
```

**Comment by dfm** [comment]
Are you maybe getting your IP address blocked for making too many requests?

**Comment by avivajpeyi** [comment]
Yeah -- that may be the issue. Strange that no error was thrown.

Im checking the `~700` TOIs that we previously noted to have 2-min cadence data again on a different cluster.

```python 
from tqdm.auto import tqdm
import lightkurve as lk

def toi_has_2min_cadence_lk(toi):
    search = lk.search_lightcurve(
                    target=f"TOI {toi}",
                    mission="TESS",
                    author="SPOC",
                )
    if len(search) > 0:
        # print(f"TOI {toi} has 2-min cadence lk data")
        return True 
    else:
        # print(f"TOI {toi} does not have 2-min cadence lk data")
        return False 


has_lk = []
missing_tois = list(set(old)-set(cur))
for missing_toi in tqdm(missing_tois):
    has_lk.append(toi_has_2min_cadence_lk(missing_toi))
```

**Comment by avivajpeyi** [comment]
@dfm  -- do you know someone we can ask about how to query the list of TOIs (with 2-min cadence data) from ExoFOP?

**Comment by dfm** [comment]
This wouldn't explain the changing results, but it would be better to search with TIC ID rather than TOI number I expect, since the TIC IDs are fixed, and the TOI numbers will take some time to resolve.

**Comment by avivajpeyi** [comment]
Ok! I can set up the search to look for TIC ids with 2 min cadence data -- but is there a better way to query this than what we've been doing (Ie manually checking each candidate with a lk download call)?

**Comment by dfm** [comment]
I think your approach is sensible! These errors don't seem to be related to timeouts or limiting - it seems to be caused by name resolution, which isn't super surprising if you're querying on TOI!

**Comment by avivajpeyi** [comment]
I submitted an array-slurm job to check each TIC in parallel (#250, #251). I _think_ this gave us the correct list of TIC with 2-min cadence data (see #254) 

Now we just need to update the TIC list with new TICs (can be done with the CLI tool `update_tic_cache`)
