### ISSUE TITLE
Save posteriors as a FITS/HDF file

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#25]

**Comment by avivajpeyi** [comment]
Look into `arviz`

**Comment by dfm** [comment]
I think this is what we want: https://github.com/arviz-devs/arviz/blob/6589319d7bc596416602010e5e0998a57237ef17/arviz/data/inference_data.py#L215

**Comment by avivajpeyi** [comment]
Also found this: https://github.com/pymc-devs/pymc3/issues/2189

QS for @dfm, are we ok with
- saving the posteriors from the `pymc3.backends.base.MultiTrace` as a HDF5 file 
- load the posterior HDF5 file as a pandas DF 
- not having the loaded object be a `pymc3.backends.base.MultiTrace` 

If we are ok with saving/loading the posteriors from a `pd.DataFrame`, then 
```
posteriors = pm.trace_to_dataframe(trace)
```
makes it quite easy :)

**Comment by dfm** [comment]
I think the following would be a better procedure:

```python
import pymc3 as pm
import arviz as az
with pm.Model() as model:
    x = pm.Normal("x")
    trace = pm.sample()
    data = az.from_pymc3(trace)
data.to_netcdf("chain.netcdf")
```

Then we could load it using:

```python
import arviz as az
new_data = az.from_netcdf("chain.netcdf")
```

This has the benefit that it stores all the sampling metadata as well as the samples themselves. We could do that manually, but this is probably better!
