### ISSUE TITLE
gh-pages broken 

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#36]
The work I did for issue #31  broke gh-pages 😅 

I have the `notebooks/` with the previous version of the notebooks [on my fork](https://github.com/avivajpeyi/tess-atlas/tree/gh-pages), and can merge that into gh-pages

**Comment by dfm** [comment]
That's fine! Let's just leave it broken for now. I don't think anyone was depending on it! I'm hoping to set up a version on a server at work once we have a working prototype.
