### ISSUE TITLE
Eccentricity calculations are wrong

### ISSUE THREAD

**Issue by dfm** [dfm/tess-atlas#46]
The duration parameter is never used but it should be passed to the `KeplerianOrbit` which would then make `rho_circ` have one entry for each planet. See here: https://gallery.exoplanet.codes/en/latest/tutorials/quick-tess/#The-probabilistic-model

Then we'll also need to update the eccentricity calculation. I think that something like this would work: https://github.com/exoplanet-dev/tess.world/blob/main/src/tess_world/templates/post.ipynb

**Comment by avivajpeyi** [comment]
While going over the eccentricty code that we currently have, I noticed the following: 
```
star = Catalogs.query_object(
        f"TIC {tic_number}", catalog="TIC", radius=0.001
    )
```
Are we not using the info on each TOI's star in our priors because that would prevent the PE from being "homogeneous"?

**Comment by dfm** [comment]
I think this is there because in the tutorial we don't have TIC values at that point. For the atlas I think it would be totally reasonable to use the values we already have.
