### ISSUE TITLE
Use Logging module

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#55]
@dfm Would it be ok I swap out `print`s with the logging module? I would like to add in dome debug logs (currently, I manually add some print statements for debugging and remove them before committing). 

Now that we are working in `.py` files, these would also be hidden from the user so hopefully, the debug logs wont get in the way :)

**Comment by dfm** [comment]
Sounds like a plan!

**Comment by avivajpeyi** [comment]
Completed in #60
