### ISSUE TITLE
Error while downloading lightcurve

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#81]
## Steps to reproduce:
`run_toi 4391` (after `python setup.py develop`)

## toi_4391

Error while trying to download lightcurve data... Hmm
``` python
INFO:root:Searching for lightkurve data with target='TIC 66620917', mission='TESS'
No data found for target "TIC 66620917".
ERROR:lightkurve.search:No data found for target "TIC 66620917".
```

``` python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-ceeecf8aa2aa> in <module>
----> 1 tic_entry = TICEntry.generate_tic_from_toi_number(toi=TOI_NUMBER)

~/Documents/projects/tess/tess-atlas/src/tess_atlas/data.py in generate_tic_from_toi_number(cls, toi, tic_data)
    295 
    296         # Load lighcurve for TIC
--> 297         lightcurve = LightCurveData.from_mast(tic=tic_number)
    298 
    299         candidates = []

~/Documents/projects/tess/tess-atlas/src/tess_atlas/data.py in from_mast(cls, tic)
    100 
    101         # Restrict to short cadence no "fast" cadence
--> 102         search = search[np.where(search.table["t_exptime"] == 120)]
    103 
    104         logging.info(

~/anaconda3/envs/phase-marginalisation-test/lib/python3.7/site-packages/astropy/table/table.py in __getitem__(self, item)
   1865     def __getitem__(self, item):
   1866         if isinstance(item, str):
-> 1867             return self.columns[item]
   1868         elif isinstance(item, (int, np.integer)):
   1869             return self.Row(self, item)

~/anaconda3/envs/phase-marginalisation-test/lib/python3.7/site-packages/astropy/table/table.py in __getitem__(self, item)
    244         """
    245         if isinstance(item, str):
--> 246             return OrderedDict.__getitem__(self, item)
    247         elif isinstance(item, (int, np.integer)):
    248             return list(self.values())[item]

KeyError: 't_exptime'
```

## Other tois with the same error:

- toi_3921
- toi_1160
- toi_1454
- toi_1564
- toi_2347
- toi_2561
- toi_2684
- toi_2699
- toi_2701
- toi_2717
- toi_2723
- toi_2745
- toi_3075

## Notes: 
on trying to manually rerun the download function, I get the following error: 
```
INFO:root:Searching for lightkurve data with target='TIC 301343785', mission='TESS'
INFO:root:Downloading 0 observations of light curve data (TIC 301343785)
/usr/local/lib/python3.9/site-packages/lightkurve-2.0.10-py3.9.egg/lightkurve/search.py:414: LightkurveWarning: Cannot download from an empty search result.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ceeecf8aa2aa> in <module>
----> 1 tic_entry = TICEntry.generate_tic_from_toi_number(toi=TOI_NUMBER)

~/Documents/projects/tess/tess-atlas/src/tess_atlas/data.py in generate_tic_from_toi_number(cls, toi, tic_data)
    295 
    296         # Load lighcurve for TIC
--> 297         lightcurve = LightCurveData.from_mast(tic=tic_number)
    298 
    299         candidates = []

~/Documents/projects/tess/tess-atlas/src/tess_atlas/data.py in from_mast(cls, tic)
    108         data = search.download_all()
    109         if data is None:
--> 110             raise ValueError(f"No light curves for TIC {tic}")
    111         logging.info("Completed light curve data download")
    112         data = data.stitch()

ValueError: No light curves for TIC 301343785
```

Here is some additional data: 

| Param                          | Val                            |
|--------------------------------|--------------------------------|
| TIC ID                         | 237770757                      |
| TOI                            | 2745.01                        |
| Previous CTOI                  | NaN                            |
| Master                         | 3                              |
| SG1A                           | 4                              |
| SG1B                           | 3                              |
| SG2                            | 3                              |
| SG3                            | 1                              |
| SG4                            | 4                              |
| SG5                            | 4                              |
| ACWG ESM                       | 119.8                          |
| ACWG TSM                       | 178.1                          |
| Time Series Observations       | 0                              |
| Spectroscopy Observations      | 0                              |
| Imaging Observations           | 0                              |
| TESS Disposition               | PC                             |
| TFOPWG Disposition             | PC                             |
| TESS Mag                       | 11.9685                        |
| TESS Mag err                   | 0.006                          |
| Planet Name                    | NaN                            |
| Pipeline Signal ID             | 1                              |
| Source                         | qlp                            |
| RA                             | 06:57:30.66                    |
| Dec                            | 03:59:38.53                    |
| PM RA (mas/yr)                 | -1.8                           |
| PM RA err (mas/yr)             | 1.9                            |
| PM Dec (mas/yr)                | -4.4                           |
| PM Dec err (mas/yr)            | 2.0                            |
| Epoch (BJD)                    | 2459211.945554                 |
| Epoch (BJD) err                | 0.000559                       |
| Period (days)                  | 1.793288                       |
| Period (days) err              | 0.000002                       |
| Duration (hours)               | 3.299                          |
| Duration (hours) err           | 0.092                          |
| Depth (mmag)                   | 17.699847                      |
| Depth (mmag) err               | 0.001401                       |
| Depth (ppm)                    | 16170.0                        |
| Depth (ppm) err                | 1.29029                        |
| Planet Radius (R_Earth)        | 22.7665                        |
| Planet Radius (R_Earth) err    | NaN                            |
| Planet Insolation (Earth Flux) | 5108.84                        |
| Planet Equil Temp (K)          | NaN                            |
| Planet SNR                     | 102.0                          |
| Stellar Distance (pc)          | 744.184                        |
| Stellar Distance (pc) err      | NaN                            |
| Stellar Eff Temp (K)           | 7122.0                         |
| Stellar Eff Temp (K) err       | NaN                            |
| Stellar log(g) (cm/s^2)        | NaN                            |
| Stellar log(g) (cm/s^2) err    | NaN                            |
| Stellar Radius (R_Sun)         | 1.74                           |
| Stellar Radius (R_Sun) err     | NaN                            |
| Stellar Metallicity            | NaN                            |
| Stellar Metallicity err        | NaN                            |
| Sectors                        | 6,33                           |
| Date TOI Alerted (UTC)         | 2021-06-03                     |
| Date TOI Updated (UTC)         | 2021-06-03                     |
| Date Modified                  | 2021-08-19 00:00:00            |
| Comments                       | found in faint-star QLP search |

The qlp search has lightcurves tho:
https://archive.stsci.edu/hlsp/qlp

**Comment by avivajpeyi** [comment]
# Taking a closer look at TOI 2347
TIC 301343785
[ExoFop Entry](https://exofop.ipac.caltech.edu/tess/target.php?id=301343785)

**Comment by dfm** [comment]
If you think that there should be data for this TIC on the archive, open an issue on the `KeplerGO/lightkurve` repo!

**Comment by avivajpeyi** [comment]
Yea! I opened an issue on lightkurve: https://github.com/lightkurve/lightkurve/issues/1140
Hopefully, they might know what's up with these TOIs.

**Comment by barentsen** [comment]
I believe this issue can be closed. ❌

Over in lightkurve/lightkurve#1140 I was unable to reproduce the problem and concluded that the data for TOI 4391 was likely unavailable for a brief period of time due to maintenance at the MAST data archive.

@avivajpeyi Please do report back if you believe the issue hasn't been resolved.  Thanks for reporting! :+1:
