### ISSUE TITLE
Error at the start of sampling

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#84]
## Steps to reproduce:
`run_toi 1950` (after `python setup.py develop`)

## toi_1950
1 chain finished, however, the 2nd chain had the following error:
```
    3     with model:
      4         samples_trace = pmx.sample(
----> 5             tune=2000, draws=2000, chains=2, cores=1, start=init_params
      6         )
      7         return samples_trace

...

LinAlgError: failed to factorize or solve matrix
Apply node that caused the error: FactorOp{quiet=False}(Elemwise{add,no_inplace}.0, Join.0, Join.0, Elemwise{Composite{exp((i0 * i1 * i2))}}.0)

```

Looks very similar to the optimization error.

**Comment by dfm** [comment]
This is caused by the Gaussian Process. Let me look into this one - I have various strategies for this kind of issue.

**Comment by dfm** [comment]
See #80 instead.
