### ISSUE TITLE
Error with missing initial period guess 

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#85]
## Steps to reproduce:
`run_toi 2098` (after `python setup.py develop`)

## toi_2098

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-8b33204d7e75> in <module>
      1 planet_transit_model, params, gp = build_planet_transit_model(tic_entry)
----> 2 test_model(planet_transit_model)

<ipython-input-1-12077ca46731> in test_model(model)
    116         test_prob = model.check_test_point()
    117         test_prob.name = "log P(test-point)"
--> 118         assert not test_prob.isnull().values.any(), test_prob
    119         test_pt = pd.Series(
    120             {

AssertionError: 
d_log__                 -3.22
r_log__                 -0.92
b_impact__              -1.39
t0_interval__           -2.39
p_1_lowerbound__          NaN
f0                      -3.22
u_quadlimbdark__        -2.77
jitter_log__             0.11
sigma_log__              0.11
rho_log__               -0.55
obs                -336792.18
Name: log P(test-point), dtype: float64
```

## toi_429
```
d_log__                 -3.22
r_log__                 -0.92
b_impact__              -1.39
t0_interval__           -2.46
p_1_lowerbound__          NaN
f0                      -3.22
u_quadlimbdark__        -2.77
jitter_log__             0.11
sigma_log__              0.11
rho_log__               -0.55
obs                -251559.81
Name: log P(test-point), dtype: float64
```

**Comment by dfm** [comment]
This often means that one of the parameters' test points are out of bounds. Is `p_1` a period? Are you sure that the initial value is within the allowed range?

**Comment by avivajpeyi** [comment]
To help with this, I thought we could:
- sample from our prior
- plot prior distribution corner
- overlay the initial guess as "truth" 

However, this is not as straightforward as I thought it would be! 

## Progress so far: 
- `pymc3` has a `pm.sample_prior_predictive` function
- `pm.sample_prior_predictive` doesn't work with our full model (when we add priors + likelihood function) 
    - This is because of the `GP` we are using (not the standard GP expected by `pymc3`
    - This is why we use `pmx.sample` rather than `pm.sample`
- I can call `pm.sample_prior_predictive` before I add the GP likelihood to the model 
    - `pm.sample_prior_predictive` giving me a dict with lots of data (more than just samples from my random vars):
```
r (500, 1)
tmax (500, 1)
tmax_1 (500,)
u_quadlimbdark__ (2, 2)
d (500, 1)
rho_log__ (500,)
jitter (500,)
tmax_1_interval__ (500,)
b_impact__ (500, 1)
d_log__ (500, 1)
p (500, 1)
rho (500,)
b (500, 1)
t0 (500, 1)
r_log__ (500, 1)
u (500, 2)
jitter_log__ (500,)
lightcurves (500, 18094, 1)
sigma (500,)
t0_interval__ (500, 1)
sigma_log__ (500,)
rho_circ (500, 1)
f0 (500,)
```

- Next step: 
    - Only grab the sample from my priors (ie don't grab 'lightcurves', 'r_log', etc) 
    - Plot corner of samples with the initial guess
    - Initial guess should be inside the priors

**Comment by dfm** [comment]
I was asking a simpler question: what is the actual testval and prior that's being used for the nan parameter. I bet there's just an issue with initialization that's putting it out of bounds!

PS the point about pmx vs pm for sampling isn't correct. You could use pm.sample, but it wouldn't handle degeneracies without some extra settings and it uses a different tuning schedule. It's true that celerite2 doesn't support prior sampling as written, but that's a different point!

**Comment by avivajpeyi** [comment]
Ah yeah what you've suggested is much simpler, and will help us pinpoint the issue! 

I _think_ i may have found our 🐛: Missing period data

- [toi_2098](https://exofop.ipac.caltech.edu/tess/target.php?id=356700488) has a period of 0 in its ExoFop entry
- [toi_429](https://exofop.ipac.caltech.edu/tess/target.php?id=259592689) has no period in its ExoFop entry

**Comment by avivajpeyi** [comment]
RE Pmx vs pm: interesting! I should take a closer look at what's going on under the hood.

**Comment by avivajpeyi** [comment]
@dfm any suggestions on how to handle the missing period initial value?  Currently, missing period data is read in as `period=0` (which is what causes the issue)

**Comment by dfm** [comment]
Good question - I'd say maybe skip them for now? They're probably single transits? What's our status on that these days?

**Comment by avivajpeyi** [comment]
Ah that makes sense -- ill test some out. 

I added in the 'tmax' parameterization in #76, will try to run a few analyses this weekend for single transit systems and see how I go.
