### ISSUE TITLE
Estimate runtime/CPU hours required for running all the fits

### ISSUE THREAD

**Issue by dfm** [dfm/tess-atlas#90]
This way I can either get you access to our cluster or run the scripts myself over here.

**Comment by avivajpeyi** [comment]
Assuming we use the currect sampler settings and that no jobs fail, running 4.5K TOIs would take ~10.5K CPU hours. Thats doesn't seem too bad! 

![run_stats](https://user-images.githubusercontent.com/15642823/132984633-4f18ec66-26e5-46e7-ab3a-9a73afe7054b.png)

Im happy to keep running on [OzStar](https://supercomputing.swin.edu.au/ozstar/) if there are CPU hour limitations on your cluster. However, we might still need to `scp` the files over to your cluster after processing!

**Comment by dfm** [comment]
Ok great! There aren't specific constraints over here, but they do make it somewhat difficult to get external accounts. I'll keep you posted!

**Comment by avivajpeyi** [comment]
I think we've figured out how to run on Ozstar and host the pages on Nectar so no need for this!
