### ISSUE TITLE
Funky Phase Plots --> Something wrong during sampling?

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#94]
#### Some of the phase plots look gorgeous! 
![iTerm2 fzLZjQ phase_plot_1](https://user-images.githubusercontent.com/15642823/132985545-527ab330-1bc2-4a07-a251-720eb5274911.png)
![iTerm2 xpUY5s phase_plot_1](https://user-images.githubusercontent.com/15642823/132985562-91c3563e-ae7d-421f-9385-75e45bebaf84.png)

#### However, some others looks sketchy: 

![iTerm2 CAAqGL phase_plot_1](https://user-images.githubusercontent.com/15642823/132985575-6e7d73cf-84ec-407c-b097-8eaf08425ff4.png)
![iTerm2 cqyySu phase_plot_1](https://user-images.githubusercontent.com/15642823/132985579-f32116de-1990-4f2c-8a28-6a9aa91d9149.png)
![iTerm2 rQukmB phase_plot_1](https://user-images.githubusercontent.com/15642823/132985583-5d12b5d1-d8e7-413a-ac89-fef307613b7e.png)

Any thoughts on these?

**Comment by dfm** [comment]
Some thoughts:

1. The first failure here looks like a plotting issue to me. Perhaps a "mean" flux isn't getting properly added or subtracted somewhere? I would expect the baseline in the data to be at zero in that plot.
2. The second looks like a convergence issue. The duration is just straight wrong. Maybe we need to check our priors to make sure that they're broad enough to allow the right parameters.
3. The third looks like an initialization problem. I'd say that the initial guess for the period is wrong. Can you double check the non-folded version to make sure that it makes sense?

**Comment by avivajpeyi** [comment]
## TOI 2148: non-zero baseline flux
Interesting: the relative flux appears to be oscilating. 

|init model| phase plot|
|-------|------|
|![lk]|![phase]|

Need to check the phase-plotting routine.


[lk]: https://user-images.githubusercontent.com/15642823/134438015-2ae27f15-0b8f-40a4-9ec0-bc0263a20a46.png
[phase]: https://user-images.githubusercontent.com/15642823/134438076-122f7d36-e280-4ff7-9c78-61f73f6db3d8.png

**Comment by avivajpeyi** [comment]
## TOI 1991

**Comment by avivajpeyi** [comment]
## TOI 1982

**Comment by avivajpeyi** [comment]
- [ ] #103 
- [ ] #102 
- [ ] #101

**Comment by avivajpeyi** [comment]
Refer to the individual issues
